# docker-compose.yml
version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=*
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
  web:
    build: ./
    #      dockerfile: Dockerfile
    #      context: ./Path
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db