apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: joeyhd/staging-weight:123
        ports:
        - containerPort: 8080
        env:
        - name: PGPASSWORD # postgres password
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: PGPASSWORD
        - name: PG_HOST # postgres url used to access the db
          valueFrom:
            configMapKeyRef: ###
              name: web-secret
              key: PG_HOST
        - name: OKTA_CLIENT_ID # Okta client id
          valueFrom:
            secretKeyRef: ###
              name: web-secret
              key: OKTA_CLIENT_ID
        - name: OKTA_CLIENT_SECRET # Okta Client secret
          valueFrom:
            secretKeyRef: ###
              name: web-secret
              key: OKTA_CLIENT_SECRET
        - name: HOST_URL # web url - transferred to okta
            valueFrom:
              configMapKeyRef: ###
                name: web-config
                key: HOST_URL
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 30100 # This is for service type NodePort